### ISSUE TITLE
Integration not loading entities.

### ISSUE THREAD

**Issue by striker30345** [hokiebrian/eia_hourly_demand#1]
The integration has stopped loading entities for me. Below are related logs and a screenshot of the integration's page.

Logger: homeassistant.components.sensor
Source: custom_components/eia_hourly_demand/sensor.py:65
Integration: Sensor (documentation, issues)
First occurred: 9:19:32 AM (1 occurrences)
Last logged: 9:19:32 AM

eia_hourly_demand: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 537, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in async_device_update
    await self.async_update()
  File "/config/custom_components/eia_hourly_demand/sensor.py", line 65, in async_update
    self._state = json.dumps(data["response"]["data"][0]["value"])
                             ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

![image](https://github.com/hokiebrian/eia_hourly_demand/assets/75173330/7bed0370-b2f5-4e1e-b615-f6db72290bd2)

![image](https://github.com/hokiebrian/eia_hourly_demand/assets/75173330/1929ee1f-72f2-4b13-8a07-e9471cb868a1)

![image](https://github.com/hokiebrian/eia_hourly_demand/assets/75173330/f22bdd31-2174-4bfa-baa2-9ca53228d84d)

**Comment by striker30345** [comment]
It has started working again.

![image](https://github.com/hokiebrian/eia_hourly_demand/assets/75173330/372becc9-8110-45d0-b2c9-2525879c0ab7)

**Comment by hokiebrian** [comment]
Thanks - looks like there was an API issue for the past few days, data wasn't being refreshed. I added some better error handling so it's a nice log message the next time this happens. v1.0.10 has the updates.
